USE CoLink;

insert into GroupChat (EventId, Monitor, Name) values (1, 5, 'Ctrl Z Gang');
insert into GroupChat (EventId, Monitor, Name) values (2, 63, 'The Chat Pack');
insert into GroupChat (EventId, Monitor, Name) values (3, 49, 'Group Chat Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (4, 1, 'LOL Express');
insert into GroupChat (EventId, Monitor, Name) values (5, 62, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (6, 21, 'The LOL Castle');
insert into GroupChat (EventId, Monitor, Name) values (7, 46, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (8, 76, 'The Banter House');
insert into GroupChat (EventId, Monitor, Name) values (9, 14, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (10, 35, 'The Laugh Lounge');
insert into GroupChat (EventId, Monitor, Name) values (11, 45, 'Giggles & Grins');
insert into GroupChat (EventId, Monitor, Name) values (12, 36, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (13, 51, 'Chat Party');
insert into GroupChat (EventId, Monitor, Name) values (14, 75, 'Scroll Patrol');
insert into GroupChat (EventId, Monitor, Name) values (15, 73, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (16, 66, 'Snap Kings');
insert into GroupChat (EventId, Monitor, Name) values (17, 69, 'The Message Mavericks');
insert into GroupChat (EventId, Monitor, Name) values (18, 6, 'Group Chat Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (19, 27, 'The Inbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (20, 14, 'Texts in Progress');
insert into GroupChat (EventId, Monitor, Name) values (21, 48, 'Pinging Pals');
insert into GroupChat (EventId, Monitor, Name) values (22, 69, 'Message Mavericks');
insert into GroupChat (EventId, Monitor, Name) values (23, 15, 'Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (24, 9, 'Kin Connection');
insert into GroupChat (EventId, Monitor, Name) values (25, 1, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (26, 63, 'No Chill Zone');
insert into GroupChat (EventId, Monitor, Name) values (27, 72, 'The Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (28, 11, 'Glitter Gang');
insert into GroupChat (EventId, Monitor, Name) values (29, 48, 'The Chat Patrol');
insert into GroupChat (EventId, Monitor, Name) values (30, 44, 'The LOL Lounge');
insert into GroupChat (EventId, Monitor, Name) values (31, 54, 'Textual Friends');
insert into GroupChat (EventId, Monitor, Name) values (32, 1, 'Gif Queens');
insert into GroupChat (EventId, Monitor, Name) values (33, 7, 'The Silent Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (34, 52, 'LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (35, 55, 'The LOL Factory');
insert into GroupChat (EventId, Monitor, Name) values (36, 24, 'Winterfell Whatsapp');
insert into GroupChat (EventId, Monitor, Name) values (37, 76, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (38, 58, 'The Text Exchange');
insert into GroupChat (EventId, Monitor, Name) values (39, 35, 'The LOL Lounge');
insert into GroupChat (EventId, Monitor, Name) values (40, 56, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (41, 46, 'The Social Circle');
insert into GroupChat (EventId, Monitor, Name) values (42, 39, 'Meme Queens');
insert into GroupChat (EventId, Monitor, Name) values (43, 72, 'The Textual Rulers');
insert into GroupChat (EventId, Monitor, Name) values (44, 39, 'LOLators');
insert into GroupChat (EventId, Monitor, Name) values (45, 30, 'Reply Guys');
insert into GroupChat (EventId, Monitor, Name) values (46, 56, 'The Dream Catchers');
insert into GroupChat (EventId, Monitor, Name) values (47, 57, 'The Talk Show');
insert into GroupChat (EventId, Monitor, Name) values (48, 31, 'The Banter Bunch');
insert into GroupChat (EventId, Monitor, Name) values (49, 18, 'Rant Room');
insert into GroupChat (EventId, Monitor, Name) values (50, 40, 'Talk-o-Bout It');
insert into GroupChat (EventId, Monitor, Name) values (51, 60, 'The Awkward Club');
insert into GroupChat (EventId, Monitor, Name) values (52, 12, 'Stardust Squad');
insert into GroupChat (EventId, Monitor, Name) values (53, 75, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (54, 68, 'Pixie Dust Posse');
insert into GroupChat (EventId, Monitor, Name) values (55, 35, 'The Chill Zone');
insert into GroupChat (EventId, Monitor, Name) values (56, 63, 'Chatastrophe');
insert into GroupChat (EventId, Monitor, Name) values (57, 63, 'The Laughing Lounge');
insert into GroupChat (EventId, Monitor, Name) values (58, 10, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (59, 52, 'Glitter Gang');
insert into GroupChat (EventId, Monitor, Name) values (60, 77, 'Teatro Carcano El Bella E La Bestia');
insert into GroupChat (EventId, Monitor, Name) values (61, 7, 'Late Night Crew');
insert into GroupChat (EventId, Monitor, Name) values (62, 30, 'The Chatty Cathys');
insert into GroupChat (EventId, Monitor, Name) values (63, 30, 'Sarcasm Society');
insert into GroupChat (EventId, Monitor, Name) values (64, 49, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (65, 21, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (66, 18, 'Tech Talkers');
insert into GroupChat (EventId, Monitor, Name) values (67, 65, 'Chatting Champs');
insert into GroupChat (EventId, Monitor, Name) values (68, 24, 'LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (69, 43, 'Lifeline Squad');
insert into GroupChat (EventId, Monitor, Name) values (70, 77, 'Agevolazioni Orchestra Filarmonica');
insert into GroupChat (EventId, Monitor, Name) values (71, 76, 'Keep It 100');
insert into GroupChat (EventId, Monitor, Name) values (72, 70, 'The Wanderlusts');
insert into GroupChat (EventId, Monitor, Name) values (73, 55, 'Coffee Break Crew');
insert into GroupChat (EventId, Monitor, Name) values (74, 16, 'Text Avengers');
insert into GroupChat (EventId, Monitor, Name) values (75, 49, 'The Meme Team');
insert into GroupChat (EventId, Monitor, Name) values (76, 16, 'Emoji Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (77, 50, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (78, 16, 'Talk-o-Bout It');
insert into GroupChat (EventId, Monitor, Name) values (79, 3, 'Squad Goals');
insert into GroupChat (EventId, Monitor, Name) values (80, 77, 'Collaborazione con Ponder');
insert into GroupChat (EventId, Monitor, Name) values (81, 18, 'Texts in Progress');
insert into GroupChat (EventId, Monitor, Name) values (82, 4, 'Chaotic Neutral');
insert into GroupChat (EventId, Monitor, Name) values (83, 42, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (84, 49, 'Just Vibing');
insert into GroupChat (EventId, Monitor, Name) values (85, 25, 'Shrek the Group');
insert into GroupChat (EventId, Monitor, Name) values (86, 67, 'Meme Overload');
insert into GroupChat (EventId, Monitor, Name) values (87, 2, 'Banter Empire');
insert into GroupChat (EventId, Monitor, Name) values (88, 61, 'Meme Troopers');
insert into GroupChat (EventId, Monitor, Name) values (89, 67, 'The Click Collective');
insert into GroupChat (EventId, Monitor, Name) values (90, 18, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (91, 29, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (92, 30, 'Meme Dream Team');
insert into GroupChat (EventId, Monitor, Name) values (93, 5, 'Drama Llamas');
insert into GroupChat (EventId, Monitor, Name) values (94, 51, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (95, 33, 'Next Level Banter');
insert into GroupChat (EventId, Monitor, Name) values (96, 43, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (97, 59, 'LOL Club');
insert into GroupChat (EventId, Monitor, Name) values (98, 45, 'Emoji Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (99, 70, 'Emoji Enforcers');
insert into GroupChat (EventId, Monitor, Name) values (100, 50, 'Stranger Texts');
insert into GroupChat (EventId, Monitor, Name) values (101, 76, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (102, 28, 'Ctrl + Alt + Del');
insert into GroupChat (EventId, Monitor, Name) values (103, 48, 'LOL Charisma');
insert into GroupChat (EventId, Monitor, Name) values (104, 10, 'The Unstoppables');
insert into GroupChat (EventId, Monitor, Name) values (105, 8, 'Ctrl Z Gang');
insert into GroupChat (EventId, Monitor, Name) values (106, 28, 'Chaos on Purpose');
insert into GroupChat (EventId, Monitor, Name) values (107, 10, 'Bookworms United');
insert into GroupChat (EventId, Monitor, Name) values (108, 57, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (109, 32, 'The Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (110, 74, 'Tech Talkers');
insert into GroupChat (EventId, Monitor, Name) values (111, 20, 'The Group Therapy');
insert into GroupChat (EventId, Monitor, Name) values (112, 46, 'The Vibe Society');
insert into GroupChat (EventId, Monitor, Name) values (113, 14, 'The Emoji Gods');
insert into GroupChat (EventId, Monitor, Name) values (114, 22, 'LOL Visionaries');
insert into GroupChat (EventId, Monitor, Name) values (115, 50, 'Chatman & Robins');
insert into GroupChat (EventId, Monitor, Name) values (116, 64, 'Gif Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (117, 6, 'The Roasting Room');
insert into GroupChat (EventId, Monitor, Name) values (118, 45, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (119, 51, 'Meme Mafia Bosses');
insert into GroupChat (EventId, Monitor, Name) values (120, 26, 'The LOL Lab');
insert into GroupChat (EventId, Monitor, Name) values (121, 17, 'The Vibe Society');
insert into GroupChat (EventId, Monitor, Name) values (122, 15, 'Chat Storm');
insert into GroupChat (EventId, Monitor, Name) values (123, 40, 'Text-Topia');
insert into GroupChat (EventId, Monitor, Name) values (124, 4, 'Chaos Coordinators');
insert into GroupChat (EventId, Monitor, Name) values (125, 29, 'The Textual Rulers');
insert into GroupChat (EventId, Monitor, Name) values (126, 4, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (127, 28, 'Meme Mayhem');
insert into GroupChat (EventId, Monitor, Name) values (128, 12, 'The Laugh Factory');
insert into GroupChat (EventId, Monitor, Name) values (129, 23, 'The Grin Gang');
insert into GroupChat (EventId, Monitor, Name) values (130, 53, 'Emoji Enforcers');
insert into GroupChat (EventId, Monitor, Name) values (131, 63, 'The LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (132, 53, 'Typo Queens');
insert into GroupChat (EventId, Monitor, Name) values (133, 10, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (134, 59, 'The Click Clique');
insert into GroupChat (EventId, Monitor, Name) values (135, 66, 'Next Level Banter');
insert into GroupChat (EventId, Monitor, Name) values (136, 9, 'The Cosmic Vibes');
insert into GroupChat (EventId, Monitor, Name) values (137, 62, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (138, 24, 'The Textual Rulers');
insert into GroupChat (EventId, Monitor, Name) values (139, 31, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (140, 5, 'Meme Dream Team');
insert into GroupChat (EventId, Monitor, Name) values (141, 20, 'Full-Time LOLers');
insert into GroupChat (EventId, Monitor, Name) values (142, 74, 'DIY Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (143, 49, 'Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (144, 37, 'Chaos Coordinators');
insert into GroupChat (EventId, Monitor, Name) values (145, 12, 'Puns and Roses');
insert into GroupChat (EventId, Monitor, Name) values (146, 74, 'Textual Runners');
insert into GroupChat (EventId, Monitor, Name) values (147, 20, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (148, 33, 'LOL Legends');
insert into GroupChat (EventId, Monitor, Name) values (149, 20, 'The LOL Lounge');
insert into GroupChat (EventId, Monitor, Name) values (150, 60, 'The Talkative Troupe');
insert into GroupChat (EventId, Monitor, Name) values (151, 66, 'Emoji Addicts');
insert into GroupChat (EventId, Monitor, Name) values (152, 29, 'The Chill Collective');
insert into GroupChat (EventId, Monitor, Name) values (153, 37, 'Roasted & Toasted');
insert into GroupChat (EventId, Monitor, Name) values (154, 57, 'The Talkative Tribe');
insert into GroupChat (EventId, Monitor, Name) values (155, 74, 'The Brainstormers');
insert into GroupChat (EventId, Monitor, Name) values (156, 73, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (157, 18, 'Roasted & Toasted');
insert into GroupChat (EventId, Monitor, Name) values (158, 73, 'Group Chat Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (159, 11, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (160, 40, 'The Textperts');
insert into GroupChat (EventId, Monitor, Name) values (161, 38, 'The Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (162, 67, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (163, 75, 'LOL Soldiers');
insert into GroupChat (EventId, Monitor, Name) values (164, 55, 'The Inner Circle');
insert into GroupChat (EventId, Monitor, Name) values (165, 75, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (166, 7, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (167, 41, 'Text-Topia');
insert into GroupChat (EventId, Monitor, Name) values (168, 31, 'Banter Empire');
insert into GroupChat (EventId, Monitor, Name) values (169, 14, 'Chat Life');
insert into GroupChat (EventId, Monitor, Name) values (170, 16, 'Meme Mafia');
insert into GroupChat (EventId, Monitor, Name) values (171, 70, 'The Click Collectors');
insert into GroupChat (EventId, Monitor, Name) values (172, 46, 'The LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (173, 72, 'Movie Buffs');
insert into GroupChat (EventId, Monitor, Name) values (174, 62, 'The GIF Show');
insert into GroupChat (EventId, Monitor, Name) values (175, 49, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (176, 13, 'Snap Attack');
insert into GroupChat (EventId, Monitor, Name) values (177, 47, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (178, 65, 'Just Kidding Club');
insert into GroupChat (EventId, Monitor, Name) values (179, 56, 'Insta Vibes');
insert into GroupChat (EventId, Monitor, Name) values (180, 20, 'Just Kidding Club');
insert into GroupChat (EventId, Monitor, Name) values (181, 43, 'Brainy Bunch');
insert into GroupChat (EventId, Monitor, Name) values (182, 62, 'Gif Queens');
insert into GroupChat (EventId, Monitor, Name) values (183, 68, 'Genes & Memes');
insert into GroupChat (EventId, Monitor, Name) values (184, 71, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (185, 2, 'Text Wizards');
insert into GroupChat (EventId, Monitor, Name) values (186, 65, 'The LOL Lounge');
insert into GroupChat (EventId, Monitor, Name) values (187, 4, 'Squad of the Year');
insert into GroupChat (EventId, Monitor, Name) values (188, 63, 'LOL Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (189, 33, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (190, 3, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (191, 33, 'Procrastination Central');
insert into GroupChat (EventId, Monitor, Name) values (192, 65, 'Hogwarts Express');
insert into GroupChat (EventId, Monitor, Name) values (193, 33, 'Pun Intended');
insert into GroupChat (EventId, Monitor, Name) values (194, 47, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (195, 64, 'Digital Daze');
insert into GroupChat (EventId, Monitor, Name) values (196, 41, 'Squad Up');
insert into GroupChat (EventId, Monitor, Name) values (197, 33, 'Group Chat Gurus');
insert into GroupChat (EventId, Monitor, Name) values (198, 41, 'The Group Therapy');
insert into GroupChat (EventId, Monitor, Name) values (199, 50, 'Reply Guys');
insert into GroupChat (EventId, Monitor, Name) values (200, 61, 'Snap Attack');
insert into GroupChat (EventId, Monitor, Name) values (201, 23, 'LOL Express');
insert into GroupChat (EventId, Monitor, Name) values (202, 31, 'Bookworms United');
insert into GroupChat (EventId, Monitor, Name) values (203, 44, 'Next Level Banter');
insert into GroupChat (EventId, Monitor, Name) values (204, 52, 'The Text Crew');
insert into GroupChat (EventId, Monitor, Name) values (205, 20, 'The Text Vault');
insert into GroupChat (EventId, Monitor, Name) values (206, 10, 'Laugh Legends');
insert into GroupChat (EventId, Monitor, Name) values (207, 67, 'The GIF Show');
insert into GroupChat (EventId, Monitor, Name) values (208, 63, 'LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (209, 38, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (210, 27, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (211, 25, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (212, 38, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (213, 53, 'The Daydreamers');
insert into GroupChat (EventId, Monitor, Name) values (214, 17, 'The LOL Factory');
insert into GroupChat (EventId, Monitor, Name) values (215, 52, 'Textual Friends');
insert into GroupChat (EventId, Monitor, Name) values (216, 69, 'Never Not Texting');
insert into GroupChat (EventId, Monitor, Name) values (217, 45, 'Bookworms United');
insert into GroupChat (EventId, Monitor, Name) values (218, 16, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (219, 27, 'Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (220, 2, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (221, 33, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (222, 62, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (223, 7, 'The Digital Den');
insert into GroupChat (EventId, Monitor, Name) values (224, 76, 'Keyboard Cowboys');
insert into GroupChat (EventId, Monitor, Name) values (225, 36, 'Pinging Pals');
insert into GroupChat (EventId, Monitor, Name) values (226, 76, 'Chaos on Purpose');
insert into GroupChat (EventId, Monitor, Name) values (227, 55, 'Puns and Roses');
insert into GroupChat (EventId, Monitor, Name) values (228, 45, 'Giggle Gang');
insert into GroupChat (EventId, Monitor, Name) values (229, 34, 'Group Therapy');
insert into GroupChat (EventId, Monitor, Name) values (230, 28, 'Just Vibing');
insert into GroupChat (EventId, Monitor, Name) values (231, 33, 'Gossip Gurus');
insert into GroupChat (EventId, Monitor, Name) values (232, 15, 'Late Night Philosophers');
insert into GroupChat (EventId, Monitor, Name) values (233, 24, 'The Brainstormers');
insert into GroupChat (EventId, Monitor, Name) values (234, 15, 'LOLators');
insert into GroupChat (EventId, Monitor, Name) values (235, 74, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (236, 61, 'Meme Queens');
insert into GroupChat (EventId, Monitor, Name) values (237, 77, 'Agevolazioni Serate Musicali');
insert into GroupChat (EventId, Monitor, Name) values (238, 1, 'Social Butterflies');
insert into GroupChat (EventId, Monitor, Name) values (239, 57, 'The Digital Den');
insert into GroupChat (EventId, Monitor, Name) values (240, 37, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (241, 67, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (242, 43, 'Scroll Patrol');
insert into GroupChat (EventId, Monitor, Name) values (243, 8, 'DIY Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (244, 28, 'The Group Think Tank');
insert into GroupChat (EventId, Monitor, Name) values (245, 45, 'Forever Squad');
insert into GroupChat (EventId, Monitor, Name) values (246, 35, 'The Grin Gang');
insert into GroupChat (EventId, Monitor, Name) values (247, 46, 'Chaos Chat Club');
insert into GroupChat (EventId, Monitor, Name) values (248, 3, 'The Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (249, 48, 'Text Busters');
insert into GroupChat (EventId, Monitor, Name) values (250, 30, 'LOL Legends');
insert into GroupChat (EventId, Monitor, Name) values (251, 17, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (252, 33, 'After Hours Banter');
insert into GroupChat (EventId, Monitor, Name) values (253, 48, 'The Chill Collective');
insert into GroupChat (EventId, Monitor, Name) values (254, 17, 'Textual Avengers');
insert into GroupChat (EventId, Monitor, Name) values (255, 61, 'Shrek the Group');
insert into GroupChat (EventId, Monitor, Name) values (256, 64, 'Meme Lords');
insert into GroupChat (EventId, Monitor, Name) values (257, 41, 'Gaming Legends');
insert into GroupChat (EventId, Monitor, Name) values (258, 12, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (259, 20, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (260, 49, 'Laughter Zone');
insert into GroupChat (EventId, Monitor, Name) values (261, 61, 'Snap Kings');
insert into GroupChat (EventId, Monitor, Name) values (262, 60, 'Banter Empire');
insert into GroupChat (EventId, Monitor, Name) values (263, 3, 'Roasted & Toasted');
insert into GroupChat (EventId, Monitor, Name) values (264, 18, 'The Groupies');
insert into GroupChat (EventId, Monitor, Name) values (265, 48, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (266, 9, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (267, 3, 'LOL Club');
insert into GroupChat (EventId, Monitor, Name) values (268, 28, 'The Meme Team');
insert into GroupChat (EventId, Monitor, Name) values (269, 57, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (270, 58, 'Meme Mavens');
insert into GroupChat (EventId, Monitor, Name) values (271, 68, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (272, 56, 'The Daydreamers');
insert into GroupChat (EventId, Monitor, Name) values (273, 29, 'We Share DNA');
insert into GroupChat (EventId, Monitor, Name) values (274, 28, 'Reply Guys');
insert into GroupChat (EventId, Monitor, Name) values (275, 14, 'Selfie Squad');
insert into GroupChat (EventId, Monitor, Name) values (276, 35, 'The Brainstormers');
insert into GroupChat (EventId, Monitor, Name) values (277, 7, 'The Emoji Army');
insert into GroupChat (EventId, Monitor, Name) values (278, 25, 'Laugh Legends');
insert into GroupChat (EventId, Monitor, Name) values (279, 2, 'Music Maniacs');
insert into GroupChat (EventId, Monitor, Name) values (280, 12, 'Textaholics Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (281, 12, 'Meme Overload');
insert into GroupChat (EventId, Monitor, Name) values (282, 56, 'Insta Vibes');
insert into GroupChat (EventId, Monitor, Name) values (283, 67, 'Typing Till Dawn');
insert into GroupChat (EventId, Monitor, Name) values (284, 3, 'Group Therapy Crew');
insert into GroupChat (EventId, Monitor, Name) values (285, 12, 'Meme Lords');
insert into GroupChat (EventId, Monitor, Name) values (286, 19, 'Overthinking Out Loud');
insert into GroupChat (EventId, Monitor, Name) values (287, 22, 'The Social Circle');
insert into GroupChat (EventId, Monitor, Name) values (288, 27, 'Message Mania');
insert into GroupChat (EventId, Monitor, Name) values (289, 74, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (290, 69, 'Meme Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (291, 38, 'Stranger Texts');
insert into GroupChat (EventId, Monitor, Name) values (292, 35, 'Pixie Dust Posse');
insert into GroupChat (EventId, Monitor, Name) values (293, 7, 'Gaming Legends');
insert into GroupChat (EventId, Monitor, Name) values (294, 23, 'Meme Mafia');
insert into GroupChat (EventId, Monitor, Name) values (295, 20, 'Emoji Addicts');
insert into GroupChat (EventId, Monitor, Name) values (296, 22, 'Forever Squad');
insert into GroupChat (EventId, Monitor, Name) values (297, 24, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (298, 18, 'After Hours Banter');
insert into GroupChat (EventId, Monitor, Name) values (299, 57, 'Fam-tastic');
insert into GroupChat (EventId, Monitor, Name) values (300, 19, 'Binge Watchers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (301, 55, 'Digital Daze');
insert into GroupChat (EventId, Monitor, Name) values (302, 73, 'The Family Circus');
insert into GroupChat (EventId, Monitor, Name) values (303, 64, 'The Textperts');
insert into GroupChat (EventId, Monitor, Name) values (304, 18, 'LOL Soldiers');
insert into GroupChat (EventId, Monitor, Name) values (305, 49, 'The Unsubscribed');
insert into GroupChat (EventId, Monitor, Name) values (306, 67, 'The Cosmic Vibes');
insert into GroupChat (EventId, Monitor, Name) values (307, 33, 'The Inbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (308, 23, 'Late Night Philosophers');
insert into GroupChat (EventId, Monitor, Name) values (309, 43, 'The Brainstormers');
insert into GroupChat (EventId, Monitor, Name) values (310, 46, 'Banter Central');
insert into GroupChat (EventId, Monitor, Name) values (311, 73, 'Chatter Kingdom');
insert into GroupChat (EventId, Monitor, Name) values (312, 64, 'Meme Mafia');
insert into GroupChat (EventId, Monitor, Name) values (313, 50, 'Never Not Texting');
insert into GroupChat (EventId, Monitor, Name) values (314, 9, 'Banter Bus');
insert into GroupChat (EventId, Monitor, Name) values (315, 58, 'The Avengers of Chatting');
insert into GroupChat (EventId, Monitor, Name) values (316, 13, 'Text Avengers');
insert into GroupChat (EventId, Monitor, Name) values (317, 16, 'Texts in Progress');
insert into GroupChat (EventId, Monitor, Name) values (318, 30, 'LOL Patrol');
insert into GroupChat (EventId, Monitor, Name) values (319, 23, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (320, 75, 'The Texted Out');
insert into GroupChat (EventId, Monitor, Name) values (321, 30, 'Text Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (322, 48, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (323, 35, 'Meme Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (324, 35, 'Glitter Gang');
insert into GroupChat (EventId, Monitor, Name) values (325, 29, 'Textual Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (326, 38, 'The Talkative Troupe');
insert into GroupChat (EventId, Monitor, Name) values (327, 53, 'The Chatterbugs');
insert into GroupChat (EventId, Monitor, Name) values (328, 45, 'Ping Masters');
insert into GroupChat (EventId, Monitor, Name) values (329, 59, 'LOL & Behold');
insert into GroupChat (EventId, Monitor, Name) values (330, 69, 'The LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (331, 24, 'The Meme Machine');
insert into GroupChat (EventId, Monitor, Name) values (332, 57, 'Chatman & Robins');
insert into GroupChat (EventId, Monitor, Name) values (333, 22, 'Procrastination Central');
insert into GroupChat (EventId, Monitor, Name) values (334, 73, 'Meme Mayhem');
insert into GroupChat (EventId, Monitor, Name) values (335, 39, 'Text Busters');
insert into GroupChat (EventId, Monitor, Name) values (336, 53, 'BFF Brigade');
insert into GroupChat (EventId, Monitor, Name) values (337, 53, 'Ctrl Z Gang');
insert into GroupChat (EventId, Monitor, Name) values (338, 7, 'The Inbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (339, 6, 'Vibe Check');
insert into GroupChat (EventId, Monitor, Name) values (340, 51, 'Giggle Gang');
insert into GroupChat (EventId, Monitor, Name) values (341, 57, 'Chatting Champs');
insert into GroupChat (EventId, Monitor, Name) values (342, 39, 'The Digital Den');
insert into GroupChat (EventId, Monitor, Name) values (343, 52, 'The Click Clique');
insert into GroupChat (EventId, Monitor, Name) values (344, 25, 'Foodies Forever');
insert into GroupChat (EventId, Monitor, Name) values (345, 61, 'The Idea Factory');
insert into GroupChat (EventId, Monitor, Name) values (346, 28, 'Rant Room');
insert into GroupChat (EventId, Monitor, Name) values (347, 69, 'Laughter Zone');
insert into GroupChat (EventId, Monitor, Name) values (348, 18, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (349, 42, 'Textual Ties');
insert into GroupChat (EventId, Monitor, Name) values (350, 35, 'CTRL ALT ELITE');
insert into GroupChat (EventId, Monitor, Name) values (351, 74, 'Lifeline Squad');
insert into GroupChat (EventId, Monitor, Name) values (352, 38, 'Procrastination Central');
insert into GroupChat (EventId, Monitor, Name) values (353, 39, 'The Texted Out');
insert into GroupChat (EventId, Monitor, Name) values (354, 35, 'Dynamic Digits');
insert into GroupChat (EventId, Monitor, Name) values (355, 34, 'The Dream Catchers');
insert into GroupChat (EventId, Monitor, Name) values (356, 47, 'Keyboard Cowboys');
insert into GroupChat (EventId, Monitor, Name) values (357, 62, 'Squad Goals');
insert into GroupChat (EventId, Monitor, Name) values (358, 4, 'The LOL Army');
insert into GroupChat (EventId, Monitor, Name) values (359, 57, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (360, 56, 'Textual Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (361, 55, 'Just Kidding Club');
insert into GroupChat (EventId, Monitor, Name) values (362, 60, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (363, 30, 'Chatterbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (364, 73, 'Binge Watchers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (365, 65, 'Sunday Roast Club');
insert into GroupChat (EventId, Monitor, Name) values (366, 22, 'Enchanted Entourage');
insert into GroupChat (EventId, Monitor, Name) values (367, 40, 'The Chat Shack');
insert into GroupChat (EventId, Monitor, Name) values (368, 10, 'Text Busters');
insert into GroupChat (EventId, Monitor, Name) values (369, 26, 'Over It Crew');
insert into GroupChat (EventId, Monitor, Name) values (370, 23, 'LOL & Behold');
insert into GroupChat (EventId, Monitor, Name) values (371, 33, 'Pun Intended');
insert into GroupChat (EventId, Monitor, Name) values (372, 48, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (373, 13, 'Sassy & Classy');
insert into GroupChat (EventId, Monitor, Name) values (374, 62, 'Chatter Champs');
insert into GroupChat (EventId, Monitor, Name) values (375, 4, 'Text Squad Goals');
insert into GroupChat (EventId, Monitor, Name) values (376, 18, 'Chat Party');
insert into GroupChat (EventId, Monitor, Name) values (377, 59, 'Text Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (378, 13, 'The Awkward Club');
insert into GroupChat (EventId, Monitor, Name) values (379, 5, 'Banter Buddies');
insert into GroupChat (EventId, Monitor, Name) values (380, 13, 'Textual Runners');
insert into GroupChat (EventId, Monitor, Name) values (381, 29, 'Stranger Texts');
insert into GroupChat (EventId, Monitor, Name) values (382, 9, 'The Real Ones');
insert into GroupChat (EventId, Monitor, Name) values (383, 31, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (384, 58, 'Scroll Patrol');
insert into GroupChat (EventId, Monitor, Name) values (385, 31, 'The Click Collectors');
insert into GroupChat (EventId, Monitor, Name) values (386, 12, 'The Click Crew');
insert into GroupChat (EventId, Monitor, Name) values (387, 39, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (388, 45, 'The Cosmic Vibes');
insert into GroupChat (EventId, Monitor, Name) values (389, 47, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (390, 77, 'Agevolazioni Fondazione S.');
insert into GroupChat (EventId, Monitor, Name) values (391, 50, 'Meme Monarchs');
insert into GroupChat (EventId, Monitor, Name) values (392, 36, 'Textual Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (393, 2, 'The Mandatextorian');
insert into GroupChat (EventId, Monitor, Name) values (394, 10, 'Overthinking Out Loud');
insert into GroupChat (EventId, Monitor, Name) values (395, 71, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (396, 7, 'Texts in Progress');
insert into GroupChat (EventId, Monitor, Name) values (397, 12, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (398, 62, 'Gaming Legends');
insert into GroupChat (EventId, Monitor, Name) values (399, 51, 'LOL Soldiers');
insert into GroupChat (EventId, Monitor, Name) values (400, 54, 'Office Banter HQ');
insert into GroupChat (EventId, Monitor, Name) values (401, 52, 'Chatman & Robins');
insert into GroupChat (EventId, Monitor, Name) values (402, 26, 'Tech Talkers');
insert into GroupChat (EventId, Monitor, Name) values (403, 58, 'Giggles & Grins');
insert into GroupChat (EventId, Monitor, Name) values (404, 76, 'Chillax Crew');
insert into GroupChat (EventId, Monitor, Name) values (405, 70, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (406, 60, 'Chatting Champs');
insert into GroupChat (EventId, Monitor, Name) values (407, 30, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (408, 17, 'The Awkward Turtles');
insert into GroupChat (EventId, Monitor, Name) values (409, 55, 'The Squad Cast');
insert into GroupChat (EventId, Monitor, Name) values (410, 17, 'Good Vibes Only');
insert into GroupChat (EventId, Monitor, Name) values (411, 67, 'Chatterbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (412, 61, 'Chatterbox Crew');
insert into GroupChat (EventId, Monitor, Name) values (413, 45, 'Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (414, 39, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (415, 47, 'The Digital Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (416, 70, 'Ctrl + Alt + Del');
insert into GroupChat (EventId, Monitor, Name) values (417, 6, 'Laughter Zone');
insert into GroupChat (EventId, Monitor, Name) values (418, 37, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (419, 21, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (420, 12, 'Text Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (421, 56, 'The LOL Army');
insert into GroupChat (EventId, Monitor, Name) values (422, 29, 'Tea Spillers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (423, 45, 'The Avengers of Chatting');
insert into GroupChat (EventId, Monitor, Name) values (424, 23, 'LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (425, 12, 'Emoji Addicts');
insert into GroupChat (EventId, Monitor, Name) values (426, 54, 'Snap Squad');
insert into GroupChat (EventId, Monitor, Name) values (427, 22, 'Tea Spillers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (428, 43, 'Meme Overlords');
insert into GroupChat (EventId, Monitor, Name) values (429, 59, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (430, 15, 'Chat Party');
insert into GroupChat (EventId, Monitor, Name) values (431, 72, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (432, 63, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (433, 60, 'The Snap Crew');
insert into GroupChat (EventId, Monitor, Name) values (434, 16, 'Dynamic Digits');
insert into GroupChat (EventId, Monitor, Name) values (435, 74, '2 AM Conversations');
insert into GroupChat (EventId, Monitor, Name) values (436, 39, 'Brainy Bunch');
insert into GroupChat (EventId, Monitor, Name) values (437, 44, 'Crafty Crew');
insert into GroupChat (EventId, Monitor, Name) values (438, 20, 'Fam-tastic');
insert into GroupChat (EventId, Monitor, Name) values (439, 44, 'Stranger Texts');
insert into GroupChat (EventId, Monitor, Name) values (440, 45, 'The GIF Goons');
insert into GroupChat (EventId, Monitor, Name) values (441, 33, 'Text Squad Goals');
insert into GroupChat (EventId, Monitor, Name) values (442, 18, 'Brainstorm Band');
insert into GroupChat (EventId, Monitor, Name) values (443, 31, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (444, 40, 'The Inner Circle');
insert into GroupChat (EventId, Monitor, Name) values (445, 70, 'Laugh Factory');
insert into GroupChat (EventId, Monitor, Name) values (446, 38, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (447, 18, 'Snap and Chat');
insert into GroupChat (EventId, Monitor, Name) values (448, 28, 'The Idea Factory');
insert into GroupChat (EventId, Monitor, Name) values (449, 52, 'Procrastination Central');
insert into GroupChat (EventId, Monitor, Name) values (450, 29, 'The Talkative Tribe');
insert into GroupChat (EventId, Monitor, Name) values (451, 47, 'Fitness Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (452, 24, 'Forever Squad');
insert into GroupChat (EventId, Monitor, Name) values (453, 36, 'The Digital Crew');
insert into GroupChat (EventId, Monitor, Name) values (454, 77, 'Cinete Camilano Cloud');
insert into GroupChat (EventId, Monitor, Name) values (455, 18, 'Textual Friends');
insert into GroupChat (EventId, Monitor, Name) values (456, 11, 'The Chill Collective');
insert into GroupChat (EventId, Monitor, Name) values (457, 74, 'Talk-o-Bout It');
insert into GroupChat (EventId, Monitor, Name) values (458, 24, 'Group Text Glory');
insert into GroupChat (EventId, Monitor, Name) values (459, 66, 'The Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (460, 1, 'LOL Legends');
insert into GroupChat (EventId, Monitor, Name) values (461, 48, 'Snap Squad');
insert into GroupChat (EventId, Monitor, Name) values (462, 37, 'LOL Visionaries');
insert into GroupChat (EventId, Monitor, Name) values (463, 48, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (464, 67, 'The Ping Pongers');
insert into GroupChat (EventId, Monitor, Name) values (465, 32, 'Screen Time Squad');
insert into GroupChat (EventId, Monitor, Name) values (466, 65, 'The Daydreamers');
insert into GroupChat (EventId, Monitor, Name) values (467, 55, 'Tea Spillers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (468, 64, 'Emoji Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (469, 7, 'The Cosmic Vibes');
insert into GroupChat (EventId, Monitor, Name) values (470, 27, 'The Chatterbugs');
insert into GroupChat (EventId, Monitor, Name) values (471, 24, 'Gif Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (472, 27, 'Text Avengers');
insert into GroupChat (EventId, Monitor, Name) values (473, 33, 'Overthinking Out Loud');
insert into GroupChat (EventId, Monitor, Name) values (474, 35, 'Reply Guys');
insert into GroupChat (EventId, Monitor, Name) values (475, 11, 'LOL Revolution');
insert into GroupChat (EventId, Monitor, Name) values (476, 45, 'The Caffeinated Crew');
insert into GroupChat (EventId, Monitor, Name) values (477, 51, 'The Ping Squad');
insert into GroupChat (EventId, Monitor, Name) values (478, 38, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (479, 5, 'Textual Chemistry');
insert into GroupChat (EventId, Monitor, Name) values (480, 12, 'Message Mania');
insert into GroupChat (EventId, Monitor, Name) values (481, 13, 'Textual Chemistry');
insert into GroupChat (EventId, Monitor, Name) values (482, 58, 'The Chatterbugs');
insert into GroupChat (EventId, Monitor, Name) values (483, 46, 'The Meme Exchange');
insert into GroupChat (EventId, Monitor, Name) values (484, 19, 'The Chat Patrol');
insert into GroupChat (EventId, Monitor, Name) values (485, 48, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (486, 76, 'Meme Mayhem');
insert into GroupChat (EventId, Monitor, Name) values (487, 46, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (488, 26, 'The GIF Goons');
insert into GroupChat (EventId, Monitor, Name) values (489, 42, 'The Banter House');
insert into GroupChat (EventId, Monitor, Name) values (490, 41, 'Meme Queens');
insert into GroupChat (EventId, Monitor, Name) values (491, 72, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (492, 13, 'Friends Since Forever');
insert into GroupChat (EventId, Monitor, Name) values (493, 51, 'Snap Kings');
insert into GroupChat (EventId, Monitor, Name) values (494, 48, 'Late-Night Legends');
insert into GroupChat (EventId, Monitor, Name) values (495, 7, 'The Emoji Army');
insert into GroupChat (EventId, Monitor, Name) values (496, 64, 'The Text Crew');
insert into GroupChat (EventId, Monitor, Name) values (497, 74, 'Hot Cheetos & Takis');
insert into GroupChat (EventId, Monitor, Name) values (498, 18, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (499, 2, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (500, 65, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (501, 9, 'Chatman & Robins');
insert into GroupChat (EventId, Monitor, Name) values (502, 30, 'Emoji Experts');
insert into GroupChat (EventId, Monitor, Name) values (503, 44, 'The Textual Rulers');
insert into GroupChat (EventId, Monitor, Name) values (504, 55, 'Banter Brigade');
insert into GroupChat (EventId, Monitor, Name) values (505, 46, 'Laugh Legends');
insert into GroupChat (EventId, Monitor, Name) values (506, 22, 'The Text Squad');
insert into GroupChat (EventId, Monitor, Name) values (507, 50, 'The LOLers');
insert into GroupChat (EventId, Monitor, Name) values (508, 20, 'The Social Spree');
insert into GroupChat (EventId, Monitor, Name) values (509, 51, 'Snack Time Chat');
insert into GroupChat (EventId, Monitor, Name) values (510, 58, 'Spill the Tea');
insert into GroupChat (EventId, Monitor, Name) values (511, 21, 'Brainy Bunch');
insert into GroupChat (EventId, Monitor, Name) values (512, 36, 'Fitness Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (513, 44, 'The Real Ones');
insert into GroupChat (EventId, Monitor, Name) values (514, 25, 'Stardust Squad');
insert into GroupChat (EventId, Monitor, Name) values (515, 65, 'The Text Tribe');
insert into GroupChat (EventId, Monitor, Name) values (516, 42, 'Meme Mafia');
insert into GroupChat (EventId, Monitor, Name) values (517, 21, 'BFF Brigade');
insert into GroupChat (EventId, Monitor, Name) values (518, 27, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (519, 8, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (520, 45, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (521, 6, 'Text Avengers');
insert into GroupChat (EventId, Monitor, Name) values (522, 20, 'Good Vibes Only');
insert into GroupChat (EventId, Monitor, Name) values (523, 76, 'We Share DNA');
insert into GroupChat (EventId, Monitor, Name) values (524, 37, 'The LOL Factory');
insert into GroupChat (EventId, Monitor, Name) values (525, 63, 'Insta Vibes');
insert into GroupChat (EventId, Monitor, Name) values (526, 33, 'Pings & Things');
insert into GroupChat (EventId, Monitor, Name) values (527, 6, 'Just Vibing');
insert into GroupChat (EventId, Monitor, Name) values (528, 73, 'The Click Collective');
insert into GroupChat (EventId, Monitor, Name) values (529, 1, 'The Chat Empire');
insert into GroupChat (EventId, Monitor, Name) values (530, 68, 'Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (531, 70, 'The Laugh Lounge');
insert into GroupChat (EventId, Monitor, Name) values (532, 8, 'LOLators');
insert into GroupChat (EventId, Monitor, Name) values (533, 71, 'The Ping Squad');
insert into GroupChat (EventId, Monitor, Name) values (534, 23, 'The Text Benders');
insert into GroupChat (EventId, Monitor, Name) values (535, 13, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (536, 53, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (537, 22, 'Lifeline Squad');
insert into GroupChat (EventId, Monitor, Name) values (538, 44, 'The LOL Wizards');
insert into GroupChat (EventId, Monitor, Name) values (539, 21, 'Laughter Lab');
insert into GroupChat (EventId, Monitor, Name) values (540, 1, 'Textual Warriors');
insert into GroupChat (EventId, Monitor, Name) values (541, 34, 'Fam-tastic');
insert into GroupChat (EventId, Monitor, Name) values (542, 18, 'The Social Network');
insert into GroupChat (EventId, Monitor, Name) values (543, 54, 'Binge Watchers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (544, 5, 'The Chat Patrol');
insert into GroupChat (EventId, Monitor, Name) values (545, 16, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (546, 43, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (547, 4, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (548, 64, 'Banter Buddies');
insert into GroupChat (EventId, Monitor, Name) values (549, 41, 'The Chatty Bunch');
insert into GroupChat (EventId, Monitor, Name) values (550, 76, 'Digital Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (551, 29, 'The Social Spree');
insert into GroupChat (EventId, Monitor, Name) values (552, 32, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (553, 60, 'The Meme Team');
insert into GroupChat (EventId, Monitor, Name) values (554, 36, 'LOL Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (555, 59, 'Genes & Memes');
insert into GroupChat (EventId, Monitor, Name) values (556, 64, 'Just Kidding Club');
insert into GroupChat (EventId, Monitor, Name) values (557, 27, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (558, 34, 'Message Mania');
insert into GroupChat (EventId, Monitor, Name) values (559, 62, 'The Idea Factory');
insert into GroupChat (EventId, Monitor, Name) values (560, 51, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (561, 57, 'The Message Mob');
insert into GroupChat (EventId, Monitor, Name) values (562, 71, 'The Unsubscribed');
insert into GroupChat (EventId, Monitor, Name) values (563, 32, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (564, 15, 'The Texting Titans');
insert into GroupChat (EventId, Monitor, Name) values (565, 58, 'The Banter House');
insert into GroupChat (EventId, Monitor, Name) values (566, 39, 'Chat Storm');
insert into GroupChat (EventId, Monitor, Name) values (567, 38, 'The Message Mob');
insert into GroupChat (EventId, Monitor, Name) values (568, 32, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (569, 30, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (570, 76, 'Texting Titans');
insert into GroupChat (EventId, Monitor, Name) values (571, 51, 'The Text Tribe');
insert into GroupChat (EventId, Monitor, Name) values (572, 35, 'The Talkative Tribe');
insert into GroupChat (EventId, Monitor, Name) values (573, 64, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (574, 3, 'Dynamic Digits');
insert into GroupChat (EventId, Monitor, Name) values (575, 46, 'The Unsubscribed');
insert into GroupChat (EventId, Monitor, Name) values (576, 4, 'Just Kidding Club');
insert into GroupChat (EventId, Monitor, Name) values (577, 50, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (578, 33, 'The Click Clique');
insert into GroupChat (EventId, Monitor, Name) values (579, 21, 'Movie Buffs');
insert into GroupChat (EventId, Monitor, Name) values (580, 59, 'Brainy Bunch');
insert into GroupChat (EventId, Monitor, Name) values (581, 1, 'The Text Crew');
insert into GroupChat (EventId, Monitor, Name) values (582, 29, 'LOL Legends');
insert into GroupChat (EventId, Monitor, Name) values (583, 73, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (584, 71, 'Textual Wizards');
insert into GroupChat (EventId, Monitor, Name) values (585, 5, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (586, 8, 'Message Mavericks');
insert into GroupChat (EventId, Monitor, Name) values (587, 56, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (588, 57, 'The Chatterbugs');
insert into GroupChat (EventId, Monitor, Name) values (589, 1, 'The Text Vault');
insert into GroupChat (EventId, Monitor, Name) values (590, 38, 'The Social Circle');
insert into GroupChat (EventId, Monitor, Name) values (591, 22, '2 AM Conversations');
insert into GroupChat (EventId, Monitor, Name) values (592, 65, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (593, 9, 'The LOL Wizards');
insert into GroupChat (EventId, Monitor, Name) values (594, 42, 'Home Base');
insert into GroupChat (EventId, Monitor, Name) values (595, 62, 'Deadline Crushers');
insert into GroupChat (EventId, Monitor, Name) values (596, 58, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (597, 12, 'The Chatterbugs');
insert into GroupChat (EventId, Monitor, Name) values (598, 12, 'Scroll Patrol');
insert into GroupChat (EventId, Monitor, Name) values (599, 23, 'Meme Overlords');
insert into GroupChat (EventId, Monitor, Name) values (600, 65, 'The LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (601, 15, 'Emoji Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (602, 21, 'Snap Masters');
insert into GroupChat (EventId, Monitor, Name) values (603, 5, 'Witty Committee');
insert into GroupChat (EventId, Monitor, Name) values (604, 69, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (605, 65, 'Squad Up');
insert into GroupChat (EventId, Monitor, Name) values (606, 51, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (607, 34, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (608, 24, 'Forever Squad');
insert into GroupChat (EventId, Monitor, Name) values (609, 20, 'Text Squad Goals');
insert into GroupChat (EventId, Monitor, Name) values (610, 30, 'Brainy Bunch');
insert into GroupChat (EventId, Monitor, Name) values (611, 5, 'Digital Daze');
insert into GroupChat (EventId, Monitor, Name) values (612, 68, 'Meme Dream Team');
insert into GroupChat (EventId, Monitor, Name) values (613, 38, 'Stardust Squad');
insert into GroupChat (EventId, Monitor, Name) values (614, 5, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (615, 21, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (616, 1, 'Dynamic Digits');
insert into GroupChat (EventId, Monitor, Name) values (617, 48, 'Night Shift Vibes');
insert into GroupChat (EventId, Monitor, Name) values (618, 23, 'Fellowship of the Ping');
insert into GroupChat (EventId, Monitor, Name) values (619, 9, 'The Text Legends');
insert into GroupChat (EventId, Monitor, Name) values (620, 3, 'Pinging Pals');
insert into GroupChat (EventId, Monitor, Name) values (621, 3, 'Over It Crew');
insert into GroupChat (EventId, Monitor, Name) values (622, 14, 'Ctrl Z Gang');
insert into GroupChat (EventId, Monitor, Name) values (623, 53, 'Gaggle of Gossipers');
insert into GroupChat (EventId, Monitor, Name) values (624, 64, 'LOL Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (625, 30, 'BFF Brigade');
insert into GroupChat (EventId, Monitor, Name) values (626, 32, 'The Message Mob');
insert into GroupChat (EventId, Monitor, Name) values (627, 50, 'Text Avengers');
insert into GroupChat (EventId, Monitor, Name) values (628, 21, 'The Grin Gang');
insert into GroupChat (EventId, Monitor, Name) values (629, 45, 'The Chat Empire');
insert into GroupChat (EventId, Monitor, Name) values (630, 23, 'LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (631, 48, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (632, 32, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (633, 37, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (634, 40, 'The LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (635, 66, 'The Banter Bunch');
insert into GroupChat (EventId, Monitor, Name) values (636, 76, 'Snap Scholars');
insert into GroupChat (EventId, Monitor, Name) values (637, 67, 'Friends Since Forever');
insert into GroupChat (EventId, Monitor, Name) values (638, 36, 'Laughter Lab');
insert into GroupChat (EventId, Monitor, Name) values (639, 57, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (640, 59, 'Meme Lords');
insert into GroupChat (EventId, Monitor, Name) values (641, 68, 'Typo Queens');
insert into GroupChat (EventId, Monitor, Name) values (642, 28, 'The Digital Crew');
insert into GroupChat (EventId, Monitor, Name) values (643, 30, 'The LOL Loft');
insert into GroupChat (EventId, Monitor, Name) values (644, 61, 'Zero Context Chat');
insert into GroupChat (EventId, Monitor, Name) values (645, 5, 'LOL Revolution');
insert into GroupChat (EventId, Monitor, Name) values (646, 21, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (647, 76, 'The Group Think Tank');
insert into GroupChat (EventId, Monitor, Name) values (648, 49, 'Hot Cheetos & Takis');
insert into GroupChat (EventId, Monitor, Name) values (649, 4, 'The Awkward Turtles');
insert into GroupChat (EventId, Monitor, Name) values (650, 24, 'Keyboard Cowboys');
insert into GroupChat (EventId, Monitor, Name) values (651, 44, 'Gossip Gurus');
insert into GroupChat (EventId, Monitor, Name) values (652, 32, 'Clueless but Cute');
insert into GroupChat (EventId, Monitor, Name) values (653, 37, 'Fam-tastic');
insert into GroupChat (EventId, Monitor, Name) values (654, 42, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (655, 71, 'The Mandatextorian');
insert into GroupChat (EventId, Monitor, Name) values (656, 41, 'Clueless but Cute');
insert into GroupChat (EventId, Monitor, Name) values (657, 32, 'No Filter Needed');
insert into GroupChat (EventId, Monitor, Name) values (658, 54, 'Text Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (659, 28, 'Chat Club');
insert into GroupChat (EventId, Monitor, Name) values (660, 45, 'Foodies Forever');
insert into GroupChat (EventId, Monitor, Name) values (661, 69, 'Late-Night Legends');
insert into GroupChat (EventId, Monitor, Name) values (662, 38, 'Emoji Extravaganza');
insert into GroupChat (EventId, Monitor, Name) values (663, 10, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (664, 7, 'The Caffeinated Crew');
insert into GroupChat (EventId, Monitor, Name) values (665, 26, 'Group Therapy Crew');
insert into GroupChat (EventId, Monitor, Name) values (666, 46, 'Textual Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (667, 34, 'The Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (668, 57, 'The Roasting Room');
insert into GroupChat (EventId, Monitor, Name) values (669, 76, 'Late Night Crew');
insert into GroupChat (EventId, Monitor, Name) values (670, 41, 'Never Not Texting');
insert into GroupChat (EventId, Monitor, Name) values (671, 19, 'Snacc Squad');
insert into GroupChat (EventId, Monitor, Name) values (672, 66, 'All for One');
insert into GroupChat (EventId, Monitor, Name) values (673, 60, 'Reply Guys');
insert into GroupChat (EventId, Monitor, Name) values (674, 47, 'On Read Gang');
insert into GroupChat (EventId, Monitor, Name) values (675, 33, 'The Texting Titans');
insert into GroupChat (EventId, Monitor, Name) values (676, 5, 'Text Crew Elite');
insert into GroupChat (EventId, Monitor, Name) values (677, 57, 'The Family Circus');
insert into GroupChat (EventId, Monitor, Name) values (678, 31, 'Tea Spillers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (679, 67, 'Emoji Ninjas');
insert into GroupChat (EventId, Monitor, Name) values (680, 69, 'Chaos on Purpose');
insert into GroupChat (EventId, Monitor, Name) values (681, 43, 'Talk-o-Bout It');
insert into GroupChat (EventId, Monitor, Name) values (682, 60, 'Chaos on Purpose');
insert into GroupChat (EventId, Monitor, Name) values (683, 44, 'Group Chat Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (684, 12, 'The Family Circus');
insert into GroupChat (EventId, Monitor, Name) values (685, 62, 'Pun Intended');
insert into GroupChat (EventId, Monitor, Name) values (686, 13, 'Meme Troopers');
insert into GroupChat (EventId, Monitor, Name) values (687, 14, 'The Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (688, 60, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (689, 50, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (690, 18, 'The Chatty Bunch');
insert into GroupChat (EventId, Monitor, Name) values (691, 52, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (692, 25, 'Meme Architects');
insert into GroupChat (EventId, Monitor, Name) values (693, 68, 'The Textual Beast Mode');
insert into GroupChat (EventId, Monitor, Name) values (694, 27, 'Home Base');
insert into GroupChat (EventId, Monitor, Name) values (695, 51, 'Always Online');
insert into GroupChat (EventId, Monitor, Name) values (696, 74, 'Textual Ties');
insert into GroupChat (EventId, Monitor, Name) values (697, 20, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (698, 9, 'Coffee & Chatter');
insert into GroupChat (EventId, Monitor, Name) values (699, 45, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (700, 66, 'The Unfiltered');
insert into GroupChat (EventId, Monitor, Name) values (701, 45, 'Zero Context Chat');
insert into GroupChat (EventId, Monitor, Name) values (702, 25, 'Texty Time');
insert into GroupChat (EventId, Monitor, Name) values (703, 66, 'Snap and Chat');
insert into GroupChat (EventId, Monitor, Name) values (704, 47, 'Textual Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (705, 27, 'The Grin Gang');
insert into GroupChat (EventId, Monitor, Name) values (706, 6, 'The Text Squad');
insert into GroupChat (EventId, Monitor, Name) values (707, 74, 'Music Maniacs');
insert into GroupChat (EventId, Monitor, Name) values (708, 37, 'Meme Mayhem');
insert into GroupChat (EventId, Monitor, Name) values (709, 58, 'Keyboard Warriors');
insert into GroupChat (EventId, Monitor, Name) values (710, 64, 'Text Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (711, 37, 'Typo Queens');
insert into GroupChat (EventId, Monitor, Name) values (712, 39, 'The LOL Factory');
insert into GroupChat (EventId, Monitor, Name) values (713, 45, 'Pixie Dust Posse');
insert into GroupChat (EventId, Monitor, Name) values (714, 40, 'Chat Royals');
insert into GroupChat (EventId, Monitor, Name) values (715, 71, 'The Emoji Army');
insert into GroupChat (EventId, Monitor, Name) values (716, 55, '2 AM Conversations');
insert into GroupChat (EventId, Monitor, Name) values (717, 8, 'Keyboard Cowboys');
insert into GroupChat (EventId, Monitor, Name) values (718, 20, 'Selfie Squad');
insert into GroupChat (EventId, Monitor, Name) values (719, 76, 'The LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (720, 66, 'Banter Brigade');
insert into GroupChat (EventId, Monitor, Name) values (721, 67, 'The Group Therapy');
insert into GroupChat (EventId, Monitor, Name) values (722, 37, 'Genes & Memes');
insert into GroupChat (EventId, Monitor, Name) values (723, 75, 'On Read Gang');
insert into GroupChat (EventId, Monitor, Name) values (724, 37, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (725, 71, 'Snap Scholars');
insert into GroupChat (EventId, Monitor, Name) values (726, 56, 'The Cosmic Vibes');
insert into GroupChat (EventId, Monitor, Name) values (727, 5, 'The Roasting Room');
insert into GroupChat (EventId, Monitor, Name) values (728, 62, 'The Family Circus');
insert into GroupChat (EventId, Monitor, Name) values (729, 53, 'Laugh Factory');
insert into GroupChat (EventId, Monitor, Name) values (730, 40, 'Banter Buddies');
insert into GroupChat (EventId, Monitor, Name) values (731, 73, 'The LOL Lab');
insert into GroupChat (EventId, Monitor, Name) values (732, 54, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (733, 37, 'Hogwarts Express');
insert into GroupChat (EventId, Monitor, Name) values (734, 11, 'Digital Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (735, 1, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (736, 70, 'The GIF Show');
insert into GroupChat (EventId, Monitor, Name) values (737, 38, 'The Chill Collective');
insert into GroupChat (EventId, Monitor, Name) values (738, 70, 'Snap Squad');
insert into GroupChat (EventId, Monitor, Name) values (739, 25, 'The Wanderlusts');
insert into GroupChat (EventId, Monitor, Name) values (740, 12, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (741, 28, 'Movie Buffs');
insert into GroupChat (EventId, Monitor, Name) values (742, 23, 'Textual Warriors');
insert into GroupChat (EventId, Monitor, Name) values (743, 56, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (744, 9, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (745, 13, 'The Ping Pongers');
insert into GroupChat (EventId, Monitor, Name) values (746, 77, 'Explore Pavia');
insert into GroupChat (EventId, Monitor, Name) values (747, 7, 'Full-Time LOLers');
insert into GroupChat (EventId, Monitor, Name) values (748, 62, 'Movie Buffs');
insert into GroupChat (EventId, Monitor, Name) values (749, 28, 'Clueless but Cute');
insert into GroupChat (EventId, Monitor, Name) values (750, 14, 'The Laugh Lounge');
insert into GroupChat (EventId, Monitor, Name) values (751, 8, 'Textual Friends');
insert into GroupChat (EventId, Monitor, Name) values (752, 2, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (753, 19, 'Backseat Chatters');
insert into GroupChat (EventId, Monitor, Name) values (754, 8, 'Always Online');
insert into GroupChat (EventId, Monitor, Name) values (755, 41, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (756, 25, 'Meme Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (757, 34, 'The Click Clique');
insert into GroupChat (EventId, Monitor, Name) values (758, 58, 'The Ping Parade');
insert into GroupChat (EventId, Monitor, Name) values (759, 69, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (760, 57, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (761, 64, 'Vibe Check');
insert into GroupChat (EventId, Monitor, Name) values (762, 4, 'Texting Titans');
insert into GroupChat (EventId, Monitor, Name) values (763, 43, 'The Awkward Club');
insert into GroupChat (EventId, Monitor, Name) values (764, 21, 'LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (765, 34, 'Pixie Dust Posse');
insert into GroupChat (EventId, Monitor, Name) values (766, 68, 'The Social Vibes');
insert into GroupChat (EventId, Monitor, Name) values (767, 16, 'BFF Brigade');
insert into GroupChat (EventId, Monitor, Name) values (768, 25, 'Phone Fanatics');
insert into GroupChat (EventId, Monitor, Name) values (769, 4, 'Banter Brigade');
insert into GroupChat (EventId, Monitor, Name) values (770, 41, 'The Magic Circle');
insert into GroupChat (EventId, Monitor, Name) values (771, 63, 'Chatastrophe');
insert into GroupChat (EventId, Monitor, Name) values (772, 43, 'Sunday Roast Club');
insert into GroupChat (EventId, Monitor, Name) values (773, 12, 'Selfie Squad');
insert into GroupChat (EventId, Monitor, Name) values (774, 28, 'Kin Connection');
insert into GroupChat (EventId, Monitor, Name) values (775, 70, 'The Emoji Army');
insert into GroupChat (EventId, Monitor, Name) values (776, 70, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (777, 4, 'Forever Squad');
insert into GroupChat (EventId, Monitor, Name) values (778, 38, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (779, 28, 'Bloodline Texts');
insert into GroupChat (EventId, Monitor, Name) values (780, 60, 'Sunday Roast Club');
insert into GroupChat (EventId, Monitor, Name) values (781, 2, 'Hashbrown Squad');
insert into GroupChat (EventId, Monitor, Name) values (782, 18, 'Work Wives');
insert into GroupChat (EventId, Monitor, Name) values (783, 70, 'The Grin Gang');
insert into GroupChat (EventId, Monitor, Name) values (784, 41, 'The Meme Exchange');
insert into GroupChat (EventId, Monitor, Name) values (785, 23, 'The Chill Pill Crew');
insert into GroupChat (EventId, Monitor, Name) values (786, 32, 'All Day Chatters');
insert into GroupChat (EventId, Monitor, Name) values (787, 64, 'Group Therapy');
insert into GroupChat (EventId, Monitor, Name) values (788, 19, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (789, 71, 'Office Banter HQ');
insert into GroupChat (EventId, Monitor, Name) values (790, 76, 'Social Butterflies');
insert into GroupChat (EventId, Monitor, Name) values (791, 60, 'Fellowship of the Ping');
insert into GroupChat (EventId, Monitor, Name) values (792, 66, 'The Vibe Society');
insert into GroupChat (EventId, Monitor, Name) values (793, 56, 'Textual Tension');
insert into GroupChat (EventId, Monitor, Name) values (794, 38, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (795, 31, 'The Awkward Turtles');
insert into GroupChat (EventId, Monitor, Name) values (796, 70, 'Meme Mayhem');
insert into GroupChat (EventId, Monitor, Name) values (797, 26, 'Text Busters');
insert into GroupChat (EventId, Monitor, Name) values (798, 63, 'Typing Till Dawn');
insert into GroupChat (EventId, Monitor, Name) values (799, 61, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (800, 66, 'Giggles & Grins');
insert into GroupChat (EventId, Monitor, Name) values (801, 40, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (802, 74, 'Emoji Gods');
insert into GroupChat (EventId, Monitor, Name) values (803, 50, 'The Click Creators');
insert into GroupChat (EventId, Monitor, Name) values (804, 6, 'The Roasting Room');
insert into GroupChat (EventId, Monitor, Name) values (805, 60, 'No Chill Zone');
insert into GroupChat (EventId, Monitor, Name) values (806, 38, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (807, 44, 'Chatman & Robins');
insert into GroupChat (EventId, Monitor, Name) values (808, 17, 'Game of Phones');
insert into GroupChat (EventId, Monitor, Name) values (809, 54, 'The Screen Queens');
insert into GroupChat (EventId, Monitor, Name) values (810, 22, 'Late-Night Chats');
insert into GroupChat (EventId, Monitor, Name) values (811, 1, 'Meme Lords');
insert into GroupChat (EventId, Monitor, Name) values (812, 61, 'The GIF Goons');
insert into GroupChat (EventId, Monitor, Name) values (813, 70, 'The Talkative Tribe');
insert into GroupChat (EventId, Monitor, Name) values (814, 44, 'LOL Express');
insert into GroupChat (EventId, Monitor, Name) values (815, 53, 'Talk Therapy');
insert into GroupChat (EventId, Monitor, Name) values (816, 44, 'Wi-Fi Wonders');
insert into GroupChat (EventId, Monitor, Name) values (817, 45, 'The Dream Catchers');
insert into GroupChat (EventId, Monitor, Name) values (818, 73, 'Ping Masters');
insert into GroupChat (EventId, Monitor, Name) values (819, 27, 'The Chill Zone');
insert into GroupChat (EventId, Monitor, Name) values (820, 62, 'Sassy & Classy');
insert into GroupChat (EventId, Monitor, Name) values (821, 37, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (822, 57, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (823, 39, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (824, 44, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (825, 10, 'LOL Charisma');
insert into GroupChat (EventId, Monitor, Name) values (826, 73, 'Meme Mavens');
insert into GroupChat (EventId, Monitor, Name) values (827, 59, 'Screen Time Squad');
insert into GroupChat (EventId, Monitor, Name) values (828, 64, 'The Wanderlusts');
insert into GroupChat (EventId, Monitor, Name) values (829, 30, 'Textual Therapy');
insert into GroupChat (EventId, Monitor, Name) values (830, 45, 'The Emoji Army');
insert into GroupChat (EventId, Monitor, Name) values (831, 73, 'Giggle Gang');
insert into GroupChat (EventId, Monitor, Name) values (832, 13, 'The Digital Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (833, 64, 'LOL Legends');
insert into GroupChat (EventId, Monitor, Name) values (834, 56, 'Meme Minions');
insert into GroupChat (EventId, Monitor, Name) values (835, 28, 'The Squad Chronicles');
insert into GroupChat (EventId, Monitor, Name) values (836, 21, 'Snap and Chat');
insert into GroupChat (EventId, Monitor, Name) values (837, 50, 'Laughter Lab');
insert into GroupChat (EventId, Monitor, Name) values (838, 71, 'The Talk Show');
insert into GroupChat (EventId, Monitor, Name) values (839, 1, 'Meme Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (840, 2, 'LOL Express');
insert into GroupChat (EventId, Monitor, Name) values (841, 58, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (842, 32, 'LOL Visionaries');
insert into GroupChat (EventId, Monitor, Name) values (843, 74, 'The Digital Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (844, 29, '2 AM Conversations');
insert into GroupChat (EventId, Monitor, Name) values (845, 60, 'Tea Spillers Anonymous');
insert into GroupChat (EventId, Monitor, Name) values (846, 19, 'Work Wives');
insert into GroupChat (EventId, Monitor, Name) values (847, 69, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (848, 13, 'Chat It Out');
insert into GroupChat (EventId, Monitor, Name) values (849, 23, 'Text Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (850, 56, 'The Chatty Bunch');
insert into GroupChat (EventId, Monitor, Name) values (851, 73, 'Pixie Dust Posse');
insert into GroupChat (EventId, Monitor, Name) values (852, 73, 'Gif Queens');
insert into GroupChat (EventId, Monitor, Name) values (853, 73, 'Keep Calm and Text On');
insert into GroupChat (EventId, Monitor, Name) values (854, 41, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (855, 15, 'The Ping Squad');
insert into GroupChat (EventId, Monitor, Name) values (856, 38, 'The Meme Factory');
insert into GroupChat (EventId, Monitor, Name) values (857, 70, 'Text Wizards');
insert into GroupChat (EventId, Monitor, Name) values (858, 60, 'Dumb & Dumberers');
insert into GroupChat (EventId, Monitor, Name) values (859, 41, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (860, 29, 'The Meeting That Never Ends');
insert into GroupChat (EventId, Monitor, Name) values (861, 51, 'The Dream Catchers');
insert into GroupChat (EventId, Monitor, Name) values (862, 61, 'Coffee Break Crew');
insert into GroupChat (EventId, Monitor, Name) values (863, 49, 'The Unstoppables');
insert into GroupChat (EventId, Monitor, Name) values (864, 12, 'The Ping Pongers');
insert into GroupChat (EventId, Monitor, Name) values (865, 11, 'The LOL Castle');
insert into GroupChat (EventId, Monitor, Name) values (866, 34, 'LOL Express');
insert into GroupChat (EventId, Monitor, Name) values (867, 4, 'Emoji Gods');
insert into GroupChat (EventId, Monitor, Name) values (868, 74, 'The Click Clique');
insert into GroupChat (EventId, Monitor, Name) values (869, 75, 'Squad of the Year');
insert into GroupChat (EventId, Monitor, Name) values (870, 35, 'LOL Brigade');
insert into GroupChat (EventId, Monitor, Name) values (871, 11, 'The Chat Pack');
insert into GroupChat (EventId, Monitor, Name) values (872, 63, 'The Magic Circle');
insert into GroupChat (EventId, Monitor, Name) values (873, 53, 'Text Masters');
insert into GroupChat (EventId, Monitor, Name) values (874, 75, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (875, 21, 'Meme Overlords');
insert into GroupChat (EventId, Monitor, Name) values (876, 61, 'Emoji Addicts');
insert into GroupChat (EventId, Monitor, Name) values (877, 49, 'Vibe Check');
insert into GroupChat (EventId, Monitor, Name) values (878, 1, 'Chatting Champs');
insert into GroupChat (EventId, Monitor, Name) values (879, 12, 'Message Mania');
insert into GroupChat (EventId, Monitor, Name) values (880, 63, 'Hot Cheetos & Takis');
insert into GroupChat (EventId, Monitor, Name) values (881, 18, 'Zero Context Chat');
insert into GroupChat (EventId, Monitor, Name) values (882, 28, 'The Talk Show');
insert into GroupChat (EventId, Monitor, Name) values (883, 12, 'Fam-tastic');
insert into GroupChat (EventId, Monitor, Name) values (884, 4, 'Insta Vibes');
insert into GroupChat (EventId, Monitor, Name) values (885, 60, 'LOL Club');
insert into GroupChat (EventId, Monitor, Name) values (886, 53, 'The Dream Catchers');
insert into GroupChat (EventId, Monitor, Name) values (887, 29, 'On Read Gang');
insert into GroupChat (EventId, Monitor, Name) values (888, 65, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (889, 13, 'Full-Time Chatters');
insert into GroupChat (EventId, Monitor, Name) values (890, 24, 'LOL Revolution');
insert into GroupChat (EventId, Monitor, Name) values (891, 45, 'Screen Time Squad');
insert into GroupChat (EventId, Monitor, Name) values (892, 27, 'LOL Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (893, 46, 'Group Chat Kings');
insert into GroupChat (EventId, Monitor, Name) values (894, 28, 'Late Night Philosophers');
insert into GroupChat (EventId, Monitor, Name) values (895, 2, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (896, 51, 'Work Wives');
insert into GroupChat (EventId, Monitor, Name) values (897, 34, 'Squad Up');
insert into GroupChat (EventId, Monitor, Name) values (898, 18, 'The Idea Factory');
insert into GroupChat (EventId, Monitor, Name) values (899, 71, 'The Chat Empire');
insert into GroupChat (EventId, Monitor, Name) values (900, 13, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (901, 70, 'Bookworms United');
insert into GroupChat (EventId, Monitor, Name) values (902, 50, 'The Chatty Collective');
insert into GroupChat (EventId, Monitor, Name) values (903, 51, 'Random Ramblers');
insert into GroupChat (EventId, Monitor, Name) values (904, 15, 'The Banter Battalion');
insert into GroupChat (EventId, Monitor, Name) values (905, 44, 'The Unstoppables');
insert into GroupChat (EventId, Monitor, Name) values (906, 50, 'Chillax Crew');
insert into GroupChat (EventId, Monitor, Name) values (907, 4, 'The FOMO Zone');
insert into GroupChat (EventId, Monitor, Name) values (908, 65, 'Chat Party');
insert into GroupChat (EventId, Monitor, Name) values (909, 31, 'The Screen Queens');
insert into GroupChat (EventId, Monitor, Name) values (910, 61, 'Ping Masters');
insert into GroupChat (EventId, Monitor, Name) values (911, 16, 'Tech Talkers');
insert into GroupChat (EventId, Monitor, Name) values (912, 64, 'The Brainstormers');
insert into GroupChat (EventId, Monitor, Name) values (913, 74, 'Ctrl Z Gang');
insert into GroupChat (EventId, Monitor, Name) values (914, 54, 'Music Maniacs');
insert into GroupChat (EventId, Monitor, Name) values (915, 73, 'Social Butterflies');
insert into GroupChat (EventId, Monitor, Name) values (916, 37, 'Gossip Gurus');
insert into GroupChat (EventId, Monitor, Name) values (917, 5, 'Textual Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (918, 55, 'Emoji Enthusiasts');
insert into GroupChat (EventId, Monitor, Name) values (919, 6, 'LOL Visionaries');
insert into GroupChat (EventId, Monitor, Name) values (920, 9, 'Chat Club');
insert into GroupChat (EventId, Monitor, Name) values (921, 51, 'Meme Monarchs');
insert into GroupChat (EventId, Monitor, Name) values (922, 39, 'The LOL Crew');
insert into GroupChat (EventId, Monitor, Name) values (923, 4, 'Emoji Enforcers');
insert into GroupChat (EventId, Monitor, Name) values (924, 69, 'Chat Storm');
insert into GroupChat (EventId, Monitor, Name) values (925, 60, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (926, 1, 'The Inner Circle');
insert into GroupChat (EventId, Monitor, Name) values (927, 44, 'Chatastrophe');
insert into GroupChat (EventId, Monitor, Name) values (928, 63, 'Texts in Progress');
insert into GroupChat (EventId, Monitor, Name) values (929, 76, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (930, 11, 'Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (931, 13, 'Backseat Chatters');
insert into GroupChat (EventId, Monitor, Name) values (932, 6, 'Text Wizards');
insert into GroupChat (EventId, Monitor, Name) values (933, 58, 'Textual Chemistry');
insert into GroupChat (EventId, Monitor, Name) values (934, 66, 'The Ping Parade');
insert into GroupChat (EventId, Monitor, Name) values (935, 27, 'The Message Mob');
insert into GroupChat (EventId, Monitor, Name) values (936, 50, 'The GIF Gang');
insert into GroupChat (EventId, Monitor, Name) values (937, 5, 'Meme Overload');
insert into GroupChat (EventId, Monitor, Name) values (938, 51, 'Stranger Texts');
insert into GroupChat (EventId, Monitor, Name) values (939, 6, 'The Vibers');
insert into GroupChat (EventId, Monitor, Name) values (940, 45, 'Textual Healing');
insert into GroupChat (EventId, Monitor, Name) values (941, 62, 'Emoji Overload');
insert into GroupChat (EventId, Monitor, Name) values (942, 20, 'The Roasting Room');
insert into GroupChat (EventId, Monitor, Name) values (943, 48, 'Chat Life');
insert into GroupChat (EventId, Monitor, Name) values (944, 36, 'The Groupies');
insert into GroupChat (EventId, Monitor, Name) values (945, 61, 'The LOL Squad');
insert into GroupChat (EventId, Monitor, Name) values (946, 51, 'Emoji Extravaganza');
insert into GroupChat (EventId, Monitor, Name) values (947, 32, 'The Text Tribe');
insert into GroupChat (EventId, Monitor, Name) values (948, 52, 'Clueless but Cute');
insert into GroupChat (EventId, Monitor, Name) values (949, 10, 'Tech Talkers');
insert into GroupChat (EventId, Monitor, Name) values (950, 45, 'Gaming Legends');
insert into GroupChat (EventId, Monitor, Name) values (951, 21, 'The Vibers');
insert into GroupChat (EventId, Monitor, Name) values (952, 50, 'Typo Queens');
insert into GroupChat (EventId, Monitor, Name) values (953, 27, 'Full Send Squad');
insert into GroupChat (EventId, Monitor, Name) values (954, 6, 'The Vibe Society');
insert into GroupChat (EventId, Monitor, Name) values (955, 9, 'Hogwarts Express');
insert into GroupChat (EventId, Monitor, Name) values (956, 17, 'The Chill Vibe Tribe');
insert into GroupChat (EventId, Monitor, Name) values (957, 20, 'The GIF Goons');
insert into GroupChat (EventId, Monitor, Name) values (958, 28, 'Textual Dynasty');
insert into GroupChat (EventId, Monitor, Name) values (959, 75, 'Meme Mafia Bosses');
insert into GroupChat (EventId, Monitor, Name) values (960, 19, 'The Daydreamers');
insert into GroupChat (EventId, Monitor, Name) values (961, 18, 'The LOL League');
insert into GroupChat (EventId, Monitor, Name) values (962, 30, 'Work Wives');
insert into GroupChat (EventId, Monitor, Name) values (963, 53, 'No Chill Zone');
insert into GroupChat (EventId, Monitor, Name) values (964, 16, 'Text Masterminds');
insert into GroupChat (EventId, Monitor, Name) values (965, 17, 'Spreadsheet Warriors');
insert into GroupChat (EventId, Monitor, Name) values (966, 61, 'LOL Club');
insert into GroupChat (EventId, Monitor, Name) values (967, 50, 'Meme Mafia');
insert into GroupChat (EventId, Monitor, Name) values (968, 58, 'The Texting Titans');
insert into GroupChat (EventId, Monitor, Name) values (969, 10, 'The Awkward Turtles');
insert into GroupChat (EventId, Monitor, Name) values (970, 64, 'Meme Overlords');
insert into GroupChat (EventId, Monitor, Name) values (971, 7, 'The LOL Factory');
insert into GroupChat (EventId, Monitor, Name) values (972, 47, 'The Snack Squad');
insert into GroupChat (EventId, Monitor, Name) values (973, 55, 'Chatting Champs');
insert into GroupChat (EventId, Monitor, Name) values (974, 60, 'Snack Attack');
insert into GroupChat (EventId, Monitor, Name) values (975, 61, 'Digital Dreamers');
insert into GroupChat (EventId, Monitor, Name) values (976, 66, 'The Message Mavericks');
insert into GroupChat (EventId, Monitor, Name) values (977, 54, 'Snap Attackers');
insert into GroupChat (EventId, Monitor, Name) values (978, 42, 'Virtual Vibes');
insert into GroupChat (EventId, Monitor, Name) values (979, 39, 'Lifeline Squad');
insert into GroupChat (EventId, Monitor, Name) values (980, 14, 'Chaotic Neutral');
insert into GroupChat (EventId, Monitor, Name) values (981, 43, 'LOL Soldiers');
insert into GroupChat (EventId, Monitor, Name) values (982, 11, 'The Emoji Gods');
insert into GroupChat (EventId, Monitor, Name) values (983, 47, 'Meme Dream Team');
insert into GroupChat (EventId, Monitor, Name) values (984, 53, 'The Idea Factory');
insert into GroupChat (EventId, Monitor, Name) values (985, 45, 'Bloodline Texts');
insert into GroupChat (EventId, Monitor, Name) values (986, 76, 'The Digital Den');
insert into GroupChat (EventId, Monitor, Name) values (987, 66, 'Meme Queens');
insert into GroupChat (EventId, Monitor, Name) values (988, 28, 'Giggle Gang');
insert into GroupChat (EventId, Monitor, Name) values (989, 57, 'The Squad Cast');
insert into GroupChat (EventId, Monitor, Name) values (990, 62, 'Screen Time Squad');
insert into GroupChat (EventId, Monitor, Name) values (991, 2, 'Cloud Nine Collective');
insert into GroupChat (EventId, Monitor, Name) values (992, 49, 'Group Chat Geniuses');
insert into GroupChat (EventId, Monitor, Name) values (993, 73, 'Textual Tyrants');
insert into GroupChat (EventId, Monitor, Name) values (994, 69, 'Talk-o-Bout It');
insert into GroupChat (EventId, Monitor, Name) values (995, 51, 'Text Busters');
insert into GroupChat (EventId, Monitor, Name) values (996, 34, 'Random Ramblers');
insert into GroupChat (EventId, Monitor, Name) values (997, 26, 'Dynamic Digits');
insert into GroupChat (EventId, Monitor, Name) values (998, 67, 'Giggle Gang');
insert into GroupChat (EventId, Monitor, Name) values (999, 60, 'The Avengers of Chatting');
insert into GroupChat (EventId, Monitor, Name) values (1000, 40, 'Hot Cheetos & Takis');


insert into GroupChat (EventId, Monitor, Name) values (1001, 1, 'Loving Life');
insert into GroupChat (EventId, Monitor, Name) values (1002, 3, 'Slay Squad');
insert into GroupChat (EventId, Monitor, Name) values (1003, 4, 'Happy Hour');
insert into GroupChat (EventId, Monitor, Name) values (1004, 9, 'Big Brainers');
insert into GroupChat (EventId, Monitor, Name) values (1005, 7, 'Database Bosses');
insert into GroupChat (EventId, Monitor, Name) values (1006, 19, 'Live Love Laugh');
insert into GroupChat (EventId, Monitor, Name) values (1007, 11, 'Morning Runners');
insert into GroupChat (EventId, Monitor, Name) values (1008, 14, 'Fast Coders');
insert into GroupChat (EventId, Monitor, Name) values (1009, 16, 'Crazy Gang');
insert into GroupChat (EventId, Monitor, Name) values (1010, 17, 'Amazing Group');
